### ISSUE TITLE
Setting limits for my CPU temperatures (k10temp)

### ISSUE THREAD

**Issue by birdie-github** [lm-sensors/lm-sensors#339]
I don't understand how to set limits for my Ryzen 7 3700X CPU.

This doesn't work:
```
chip "k10temp-*"
    label temp1 "CPU Primary T Control"

    set in1_max  80
    set in1_crit 85

    set in2_max  80
    set in2_crit 85

    set in3_max  80
    set in3_crit 85

    set temp1_max  80
    set temp1_crit 85
    set temp1_hyst 90

    set temp2_max  80
    set temp2_crit 85
    set temp2_hyst 90

    set temp3_max  80
    set temp3_crit 85
    set temp3_hyst 90
```

The label applies but temperature allowances not:

```
$ sensors
k10temp-pci-00c3
Adapter: PCI adapter
CPU Primary T Control:  +38.0°C  
Tdie:                   +38.0°C  
Tccd1:                  +37.8°C
```

How is this done exactly? Also, what is "hyst"?

**Comment by LiSongMWO** [comment]
I have the same problem:

```
sensors -u k10temp-pci-00c3
k10temp-pci-00c3
Adapter: PCI adapter
Tctl:
  temp1_input: 26.500
Tdie:
  temp2_input: 26.500
```

it seems as the `k10temp` module is missing the alert thresholds?
